import type { Locale } from "@/lib/locale";

export function getHomeTexts(locale: Locale) {
  if (locale === "en") {
    return {
      heroKicker: "Curated HTML5 Picks",
      heroTitle: "Launch premium browser games instantly.",
      heroSubtitle:
        "A curated portal for fast-loading HTML5 games, SEO-ready content and monetization spaces designed for retention.",
      ctaPlay: "Play now",
      ctaRegister: "Create account",
      ctaMission: "See mission",
      ctaBadge: "No installs • Full browser gameplay",
      featuredLabel: "Featured games",
      progressHubLabel: "Player progress",
      progressHubTitle: "Your run is active again",
      progressHubSubtitle:
        "Track level, streak, unread alerts and your mission without leaving the homepage.",
      rankingLabel: "Top players",
      rankingSubtitle: "A public ranking of the accounts scoring the most XP inside the portal.",
      rankingEmpty: "No ranked players yet.",
      rankBadge: "Current rank",
      nextLevelLabel: "Next level",
      missionProgressTopLabel: "Mission today",
      themesLabel: "Browse by theme",
      themesSubtitle: "See the main lanes of the catalog and jump straight to the games you want.",
      catalogLabel: "More games to play now",
      catalogSubtitle: "A wider slice of the live catalog, with less filler and more playable titles.",
      themeShelvesLabel: "Games across the main themes",
      themeShelvesSubtitle:
        "A quick pass through the strongest categories so the homepage stays game-first.",
      newLabel: "New releases",
      popularLabel: "Most played",
      continueLabel: "Continue playing",
      recommendedLabel: "Recommended for you",
      recommendedReasonLabel: "Because you like",
      missionLabel: "Today mission",
      missionGuestLabel: "Unlock your player hub",
      missionGuestTitle: "Create an account to save progress and build streaks.",
      missionGuestBody:
        "Keep your history, collect favorites and unlock levels, streaks and achievements in the portal.",
      missionProgressLabel: "Current progress",
      missionCtaGuest: "Create account",
      missionCtaPlay: "Play now",
      bannerTop: "Top banner - Home",
      bannerMiddle: "Middle banner - Home",
      blogTitle: "Growth content for gaming portals",
      blogSubtitle:
        "Articles about SEO, ad monetization and performance tactics for online game projects.",
      blogCategoryLabel: "Category",
      empty: "No published games yet.",
      readAll: "View all",
      heroChip: "Live catalog",
      heroMeta: "HTML5 • Curated • Responsive",
      continueHint: "Resume where you left off or discover the next best game for your taste.",
      statsLevel: "Level",
      statsStreak: "Streak",
      statsNotifications: "Notifications",
      anonymousHint: "Save favorites, progress and personalized recommendations.",
      heroPersonalizedContinue: "Resume your run",
      heroPersonalizedRecommended: "Recommended for your profile",
      heroPersonalizedFeatured: "Portal spotlight",
      topClicksLabel: "Hot right now",
      playInstantly: "Play instantly in your browser",
      readPost: "Read",
      achievementsLabel: "Achievement wall",
      achievementsSubtitle: "Unlocked badges stay lit. Dim ones mark the next goals to chase.",
      achievementsLockedLabel: "Locked",
      achievementsUnlockedLabel: "Unlocked",
      achievementsGuestCta: "Unlock with account",
      achievementsAccountCta: "Open profile",
    } as const;
  }

  if (locale === "es") {
    return {
      heroKicker: "Selección HTML5",
      heroTitle: "Juega títulos premium al instante en el navegador.",
      heroSubtitle:
        "Un portal curado para juegos HTML5 rápidos, contenido SEO y espacios de monetización pensados para retención.",
      ctaPlay: "Jugar ahora",
      ctaRegister: "Crear cuenta",
      ctaMission: "Ver misión",
      ctaBadge: "Sin instalación • Juego completo en navegador",
      featuredLabel: "Destacados",
      progressHubLabel: "Progreso del jugador",
      progressHubTitle: "Tu ruta sigue encendida",
      progressHubSubtitle:
        "Mira nivel, racha, alertas y misión diaria sin salir de la home.",
      rankingLabel: "Top jugadores",
      rankingSubtitle: "Un ranking público con las cuentas que más XP acumulan dentro del portal.",
      rankingEmpty: "Todavía no hay jugadores rankeados.",
      rankBadge: "Posición actual",
      nextLevelLabel: "Próximo nivel",
      missionProgressTopLabel: "Misión de hoy",
      themesLabel: "Explorar por tema",
      themesSubtitle: "Mira las rutas principales del catálogo y entra directo a los juegos que quieres jugar.",
      catalogLabel: "Más juegos para jugar ahora",
      catalogSubtitle: "Una selección más amplia del catálogo activo, con menos desvío y más juegos en la home.",
      themeShelvesLabel: "Juegos en las temáticas principales",
      themeShelvesSubtitle:
        "Un recorrido rápido por las categorías más fuertes para mantener la home centrada en juegos.",
      newLabel: "Novedades",
      popularLabel: "Más jugados",
      continueLabel: "Seguir jugando",
      recommendedLabel: "Recomendados para ti",
      recommendedReasonLabel: "Porque te gusta",
      missionLabel: "Misión de hoy",
      missionGuestLabel: "Desbloquea tu perfil de jugador",
      missionGuestTitle: "Crea una cuenta para guardar progreso y mantener rachas.",
      missionGuestBody:
        "Guarda historial, favoritos y sube de nivel con conquistas y actividad constante.",
      missionProgressLabel: "Progreso actual",
      missionCtaGuest: "Crear cuenta",
      missionCtaPlay: "Jugar ahora",
      bannerTop: "Banner superior - Home",
      bannerMiddle: "Banner medio - Home",
      blogTitle: "Contenido para crecer tu arcade",
      blogSubtitle:
        "Artículos sobre SEO, anuncios y performance para proyectos de juegos online.",
      blogCategoryLabel: "Categoría",
      empty: "Aún no hay juegos publicados.",
      readAll: "Ver todo",
      heroChip: "Catálogo activo",
      heroMeta: "HTML5 • Curado • Responsive",
      continueHint: "Retoma tus partidas recientes y descubre sugerencias basadas en tu perfil.",
      statsLevel: "Nivel",
      statsStreak: "Racha",
      statsNotifications: "Notificaciones",
      anonymousHint: "Guarda favoritos, progreso y recomendaciones personalizadas.",
      heroPersonalizedContinue: "Retoma tu partida",
      heroPersonalizedRecommended: "Recomendado para tu perfil",
      heroPersonalizedFeatured: "Destacado del portal",
      topClicksLabel: "En alta ahora",
      playInstantly: "Juega al instante en tu navegador",
      readPost: "Leer",
      achievementsLabel: "Muro de conquistas",
      achievementsSubtitle: "Las insignias encendidas ya son tuyas. Las opacas marcan el siguiente objetivo.",
      achievementsLockedLabel: "Bloqueada",
      achievementsUnlockedLabel: "Conseguida",
      achievementsGuestCta: "Desbloquear con cuenta",
      achievementsAccountCta: "Abrir perfil",
    } as const;
  }

  return {
    heroKicker: "Seleção HTML5",
    heroTitle: "Jogue games premium direto no navegador.",
    heroSubtitle:
      "Um portal curado para jogos HTML5 rápidos, conteúdo SEO e espaços de monetização pensados para retenção.",
    ctaPlay: "Jogar agora",
    ctaRegister: "Criar conta",
    ctaMission: "Ver missão",
    ctaBadge: "Sem instalação • Gameplay total no navegador",
    featuredLabel: "Jogos em destaque",
    progressHubLabel: "Progresso do jogador",
    progressHubTitle: "Sua jornada segue aquecida",
    progressHubSubtitle:
      "Acompanhe nível, streak, alertas e missão diária sem sair da home.",
    rankingLabel: "Top jogadores",
    rankingSubtitle: "Um ranking público com as contas que mais acumulam XP dentro do portal.",
    rankingEmpty: "Ainda não há jogadores no ranking.",
    rankBadge: "Posição atual",
    nextLevelLabel: "Próximo nível",
    missionProgressTopLabel: "Missão de hoje",
    themesLabel: "Explore por tema",
    themesSubtitle: "Veja as principais trilhas do catálogo e entre direto no que quer jogar.",
    catalogLabel: "Mais jogos para jogar agora",
    catalogSubtitle: "Um recorte maior do catálogo ao vivo, com menos desvio e mais jogos na home.",
    themeShelvesLabel: "Jogos nas principais temáticas",
    themeShelvesSubtitle:
      "Uma passada rápida pelas categorias mais fortes para manter a home centrada em jogos.",
    newLabel: "Lançamentos",
    popularLabel: "Mais jogados",
    continueLabel: "Continue jogando",
    recommendedLabel: "Recomendado para você",
    recommendedReasonLabel: "Porque você gosta de",
    missionLabel: "Missão de hoje",
    missionGuestLabel: "Desbloqueie seu perfil de jogador",
    missionGuestTitle: "Crie uma conta para salvar progresso e manter streaks.",
    missionGuestBody:
      "Guarde histórico, favoritos e evolua com níveis, conquistas e notificações dentro do portal.",
    missionProgressLabel: "Progresso atual",
    missionCtaGuest: "Criar conta",
    missionCtaPlay: "Jogar agora",
    bannerTop: "Banner superior - Home",
    bannerMiddle: "Banner meio - Home",
    blogTitle: "Conteúdo para crescer seu arcade",
    blogSubtitle:
      "Artigos sobre SEO, anúncios e performance para projetos de jogos online.",
    blogCategoryLabel: "Categoria",
    empty: "Ainda não há jogos publicados.",
    readAll: "Ver tudo",
    heroChip: "Catálogo ativo",
    heroMeta: "HTML5 • Curado • Responsivo",
    continueHint: "Retome suas partidas recentes e veja sugestões baseadas no seu perfil.",
    statsLevel: "Nível",
    statsStreak: "Streak",
    statsNotifications: "Notificações",
    anonymousHint: "Salve favoritos, progresso e recomendações personalizadas.",
    heroPersonalizedContinue: "Retome sua jornada",
    heroPersonalizedRecommended: "Recomendado para o seu perfil",
    heroPersonalizedFeatured: "Destaque do portal",
    topClicksLabel: "Em alta agora",
    playInstantly: "Jogue instantaneamente no navegador",
    readPost: "Ler",
    achievementsLabel: "Mural de conquistas",
    achievementsSubtitle: "As insígnias acesas já são suas. As opacas mostram o próximo alvo da jornada.",
    achievementsLockedLabel: "Bloqueada",
    achievementsUnlockedLabel: "Conquistada",
    achievementsGuestCta: "Desbloquear com conta",
    achievementsAccountCta: "Abrir perfil",
  } as const;
}