-- Enable pg_trgm extension for trigram-based ILIKE search.
-- This allows GIN indexes to accelerate `ILIKE '%query%'` queries
-- (generated by Prisma's `contains` + `mode: "insensitive"`).
-- Supabase has this extension available by default.
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- GIN trigram index on Game.title — accelerates title search
CREATE INDEX CONCURRENTLY IF NOT EXISTS "Game_title_trgm_gin"
  ON "Game" USING gin (title gin_trgm_ops);

-- GIN trigram index on Game.tags — accelerates tag search
CREATE INDEX CONCURRENTLY IF NOT EXISTS "Game_tags_trgm_gin"
  ON "Game" USING gin (tags gin_trgm_ops);

-- GIN trigram index on Game.category — accelerates category search
CREATE INDEX CONCURRENTLY IF NOT EXISTS "Game_category_trgm_gin"
  ON "Game" USING gin (category gin_trgm_ops);
